{
 "title": "Fuse Metrics",
 "description": "Fuse Metrics dashboard",
 "tags": [ "1.0" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "pod", "label": "Pod", "query": "label_values(pod)" },
   { "name": "service", "query": "label_values(service)" },
   { "name": "namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Current Memory HEAP",
   "type": "gauge",
   "description": "Memory currently being used by Fuse.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{pod=\"$pod\", area=\"heap\"})*100/sum(jvm_memory_bytes_max{pod=\"$pod\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Current Memory nonHEAP",
   "type": "gauge",
   "description": "Memory currently being used by Fuse.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{pod=\"$pod\", area=\"nonheap\"})*100/sum(jvm_memory_bytes_max{pod=\"$pod\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory Usage",
   "gridPos": { "h": 6, "w": 13, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_committed{pod=\"$pod\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{pod=\"$pod\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{pod=\"$pod\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Camel Exchanges",
   "type": "graph",
   "description": "Camel Exchanges",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_camel_ExchangesCompleted{pod=\"$pod\"})",
     "legendFormat": "Exchanges Completed"
    },
    {
     "expr": "sum(org_apache_camel_ExchangesFailed{pod=\"$pod\"})",
     "legendFormat": "Exchanges Failed"
    },
    {
     "expr": "sum(org_apache_camel_ExchangesTotal{pod=\"$pod\"})",
     "legendFormat": "Exchanges Total"
    },
    {
     "expr": "sum(org_apache_camel_ExchangesInflight{pod=\"$pod\"})",
     "legendFormat": "Exchanges Inflight"
    }
   ]
  },
  {
   "title": "Camel Processing Time",
   "type": "graph",
   "description": "Camel Processing Time",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_camel_DeltaProcessingTime{pod=\"$pod\"})",
     "legendFormat": "Delta Processing Time"
    },
    {
     "expr": "sum(org_apache_camel_LastProcessingTime{pod=\"$pod\"})",
     "legendFormat": "Last Processing Time"
    },
    {
     "expr": "sum(org_apache_camel_MaxProcessingTime{pod=\"$pod\"})",
     "legendFormat": "Max Processing Time"
    },
    {
     "expr": "sum(org_apache_camel_MinProcessingTime{pod=\"$pod\"})",
     "legendFormat": "Min Processing Time"
    },
    {
     "expr": "sum(org_apache_camel_MeanProcessingTime{pod=\"$pod\"})",
     "legendFormat": "Mean Processing Time"
    }
   ]
  },
  {
   "title": "Total Started Routes",
   "type": "graph",
   "description": "Started Routes",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_camel_StartedRoutes{pod=\"$pod\"})",
     "legendFormat": "Camel Started Routes"
    },
    {
     "expr": "sum(org_apache_camel_TotalRoutes{pod=\"$pod\"})",
     "legendFormat": "Camel Total Routes"
    }
   ]
  },
  {
   "title": "Camel Failures & Redelivries",
   "type": "graph",
   "description": "Camel Failures & Redelivries",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_camel_Redeliveries{pod=\"$pod\"})",
     "legendFormat": "Redeliveries"
    },
    {
     "expr": "sum(org_apache_camel_LastProcessingTime{pod=\"$pod\"})",
     "legendFormat": "Last Processing Time"
    },
    {
     "expr": "sum(org_apache_camel_ExternalRedeliveries{pod=\"$pod\"})",
     "legendFormat": "External Redeliveries"
    }
   ]
  }
 ]
}